version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: LLM-AAP-8.14.0
    environment:
      - node.name=node1
      - cluster.name=llm-aap
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - llm-aap
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana-llm-aap-8.14.0
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - csp.strict=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - llm-aap
    depends_on: 
      - elasticsearch

volumes:
  node1-data:
    driver: local

networks:
  llm-aap: