name: llm_env
channels:
  - defaults
dependencies:
  - python=3.10.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - altair=5.2.0
  - annotated-types=0.6.0
  - anyio=4.2.0
  - async-timeout=4.0.3
  - attrs=23.2.0
  - backoff=2.2.1
  - bcrypt=4.1.2
  - beautifulsoup4=4.12.3
  - blinker=1.7.0
  - blis=0.7.11
  - cachetools=5.3.2
  - catalogue=2.0.10
  - certifi=2023.11.17
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - chroma-hnswlib=0.7.3
  - chromadb=0.4.15
  - ci-info=0.3.0
  - click=8.1.7
  - cloudpathlib=0.16.0
  - coloredlogs=15.0.1
  - confection=0.1.4
  - configobj=5.0.8
  - configparser=6.0.0
  - cymem=2.0.8
  - dataclasses-json=0.6.3
  - Deprecated=1.2.14
  - etelemetry=0.3.1
  - exceptiongroup=1.2.0
  - fastapi=0.109.0
  - filelock=3.13.1
  - fitz=0.0.1.dev2
  - flatbuffers=23.5.26
  - frozenlist=1.4.1
  - fsspec=2023.12.2
  - gitdb=4.0.11
  - GitPython=3.1.41
  - google-auth=2.27.0
  - googleapis-common-protos=1.62.0
  - greenlet=3.0.3
  - grpcio=1.60.0
  - h11=0.14.0
  - httplib2=0.22.0
  - httptools=0.6.1
  - huggingface-hub=0.20.3
  - humanfriendly=10.0
  - ibm-cloud-sdk-core=3.18.0
  - ibm-cos-sdk=2.13.3
  - ibm-cos-sdk-core=2.13.3
  - ibm-cos-sdk-s3transfer=2.13.3
  - ibm-watson-machine-learning=1.0.344
  - idna=3.6
  - importlib-metadata=6.11.0
  - importlib-resources=6.1.1
  - isodate=0.6.1
  - Jinja2=3.1.3
  - jmespath=1.0.1
  - joblib=1.3.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - kubernetes=29.0.0
  - langchain=0.1.4
  - langchain-community=0.0.16
  - langchain-core=0.1.16
  - langcodes=3.3.0
  - langsmith=0.0.83
  - lomond=0.3.3
  - looseversion=1.3.0
  - lxml=5.1.0
  - markdown-it-py=3.0.0
  - MarkupSafe=2.1.4
  - marshmallow=3.20.2
  - mdurl=0.1.2
  - monotonic=1.6
  - mpmath=1.3.0
  - multidict=6.0.4
  - murmurhash=1.0.10
  - mypy-extensions=1.0.0
  - networkx=3.2.1
  - nibabel=5.2.0
  - nipype=1.8.6
  - nltk=3.8.1
  - numpy=1.26.3
  - nvidia-cublas-cu12=12.1.3.1
  - nvidia-cuda-cupti-cu12=12.1.105
  - nvidia-cuda-nvrtc-cu12=12.1.105
  - nvidia-cuda-runtime-cu12=12.1.105
  - nvidia-cudnn-cu12=8.9.2.26
  - nvidia-cufft-cu12=11.0.2.54
  - nvidia-curand-cu12=10.3.2.106
  - nvidia-cusolver-cu12=11.4.5.107
  - nvidia-cusparse-cu12=12.1.0.106
  - nvidia-nccl-cu12=2.18.1
  - nvidia-nvjitlink-cu12=12.3.101
  - nvidia-nvtx-cu12=12.1.105
  - oauthlib=3.2.2
  - onnxruntime=1.16.3
  - opentelemetry-api=1.22.0
  - opentelemetry-exporter-otlp-proto-common=1.22.0
  - opentelemetry-exporter-otlp-proto-grpc=1.22.0
  - opentelemetry-proto=1.22.0
  - opentelemetry-sdk=1.22.0
  - opentelemetry-semantic-conventions=0.43b0
  - overrides=7.7.0
  - packaging=23.2
  - pandas=1.5.3
  - pathlib=1.0.1
  - pillow=10.2.0
  - pip=23.3.1
  - plotly=5.18.0
  - posthog=3.3.3
  - preshed=3.0.9
  - protobuf=4.25.2
  - prov=2.0.0
  - pulsar-client=3.4.0
  - pyarrow=15.0.0
