name: watsonx.rescue_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.3
  - ibm-watson-machine-learning
  - ibm-cos-sdk
  - ibm-cloud-sdk-core
  - openai
  - chromadb==0.4.15
  - plotly
  - chardet
  - langchain
  - pypdf
  - sentence_transformers
  - streamlit
  - fitz
  - pymupdf
  - spacy
  - beautifulsoup4
  - python-dotenv~=1.0.0
